### ISSUE TITLE
Corrigir workflow de testes no Github Actions

### ISSUE THREAD

**Issue by augusto-herrmann** [gestaogovbr/api-pgd#81]
O processo de integração contínua não está funcionando.

No passo "Configure Fief at runtime", um container não consegue encontrar o outro, fazendo o workflow falhar.

```
docker-compose exec -T web sh -c "cd ./init && python configure_fief.py"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

No ambiente local de desenvolvimento, este passo, que também pode ser executado por meio do comando [`make fief-configure-instance`](https://github.com/gestaogovbr/api-pgd/blob/main/Makefile#L13C32-L13C32), funciona normalmente. Para ele funcionar, os containers precisam já estar rodando (`make up`).

**Comment by augusto-herrmann** [comment]
Corrigido pelo @vitorbellini nos commits 7938da662d68fa40302ca41e5fd0295ee5b9a628 a 65be76f413dce5350779d691a907a6d0c6cc06d0.
